name: Pre Release

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "v**"
      - "ci"
  workflow_dispatch:

concurrency:
  group: pre-release
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  pre-release:
    name: Pre Release
    needs: build
    runs-on: windows-2025
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download x86 build
        uses: actions/download-artifact@v8
        with:
          name: HelloWorld-x86
          path: artifacts/x86

      - name: Download x64 build
        uses: actions/download-artifact@v8
        with:
          name: HelloWorld-x64
          path: artifacts/x64

      - name: Rename artifacts
        shell: pwsh
        run: |
          Rename-Item -Path "artifacts/x86/HelloWorld.exe" -NewName "HelloWorld-x86.exe"
          Rename-Item -Path "artifacts/x64/HelloWorld.exe" -NewName "HelloWorld-x64.exe"

      - name: Remove ci tag locally
        run: git tag -d ci || true

      - name: Build changelog
        uses: orhun/git-cliff-action@v4
        env:
          OUTPUT: build/changelog.md
        with:
          args: --unreleased --tag "CI Build"

      - name: Update ci tag
        run: |
          git tag -f ci
          git push origin ci -f

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: build/changelog.md
          prerelease: true
          name: CI Build
          tag_name: ci
          files: |
            artifacts/x86/HelloWorld-x86.exe
            artifacts/x64/HelloWorld-x64.exe
