name: Release

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release:
    name: Release
    needs: build
    runs-on: windows-2025
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download x86 build
        uses: actions/download-artifact@v8
        with:
          name: HelloWorld-x86
          path: artifacts/x86

      - name: Download x64 build
        uses: actions/download-artifact@v8
        with:
          name: HelloWorld-x64
          path: artifacts/x64

      - name: Rename artifacts
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          Rename-Item -Path "artifacts/x86/HelloWorld.exe" -NewName "HelloWorld-${ver}-x86.exe"
          Rename-Item -Path "artifacts/x64/HelloWorld.exe" -NewName "HelloWorld-${ver}-x64.exe"

      - name: Remove ci tag locally
        run: git tag -d ci || true

      - name: Build changelog
        uses: orhun/git-cliff-action@v4
        env:
          OUTPUT: build/changelog.md
        with:
          args: --latest

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: build/changelog.md
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/x86/HelloWorld-${{ github.ref_name }}-x86.exe
            artifacts/x64/HelloWorld-${{ github.ref_name }}-x64.exe
